### ISSUE TITLE
funcion keypadRead del archivo sapi_keypad.c delay bloqueante

### ISSUE THREAD

**Issue by maximiliano-alexandroff** [epernia/sAPI#6]
Buenas como están?

He estado utilizando la función de manejo de teclado matricial de la sAPI, y en la funcion keypadRead() existe el siguiente delay bloqueante:

**delay( 50 ); // Debounce 50 ms**

Entiendo que es por el efecto antirebote pero al ser bloqueante no me permite realizar tareas compartidas con periodos menores a 50 ms. Ademas, en la funcion **tickConfig( )** de la sAPI  entiendo que solo se puede configurar periodos 1 ms a 50 ms.
En conclusión, no se puede realizar tareas compartidas haciendo uso de sapi_keypad.c y sapi_tick.c debido a este retardo bloqueante.
Espero que lo tengan en cuenta.

Saludos.

**Comment by epernia** [comment]
En el tema de delay() tenés razón, es bloqueante. En cambio las funciones de tick no, son para configurar interrupciones periódicas, lo más rápido es que interrumpa cada 1 ms y lo más lento cada 50 ms.
